theme: papermod
title: "sloonz's blog"
copyright: "This work is licensed under the [CC0 1.0 Universal Creative Commons License](https://creativecommons.org/publicdomain/zero/1.0/)."
params:
  author: sloonz
  showFullTextInRSS: true
  homeInfoParams:
    title: "sloonz's blog"
  socialIcons:
    - name: github
      title: My Github Profile
      url: https://github.com/sloonz/
    - name: rss
      title: RSS feed
      url: /index.xml
